### ISSUE TITLE
Unable to deploy the project

### ISSUE THREAD

**Issue by Abhijeetm96** [YogeshPrasanna/expense-manager-react#24]
Hi ,

   I followed all the instructions provided in your git repo but even then i am not able to run the project. Is there anything I had missed out. Please find the screenshots attached.

Please clarify the firebase initialisation process too.

![image](https://user-images.githubusercontent.com/41344280/59817981-b1663900-933f-11e9-8716-b89ab4725080.png)

![image](https://user-images.githubusercontent.com/41344280/59817938-824fc780-933f-11e9-923c-a9a8fc0a0c58.png)

**Comment by YogeshPrasanna** [comment]
@Abhijeetm96 , please update the firebase to the following version 

npm install firebase@6.2.1

I hope this would solve the issue , there was some vulnerabilities with the older versions of firebase
Do checkout , and if this solves , you can close the issue

**Comment by Abhijeetm96** [comment]
This is what i got after executing the above command
![image](https://user-images.githubusercontent.com/41344280/59995212-299c6980-9674-11e9-8734-172c2da95521.png)

just wanted to check if the firebase initialisation and deployment process is same for react as that of Angular.

**Comment by YogeshPrasanna** [comment]
Can you delete your node_modules directory, run npm cache clean --force and try again? Sounds like a package wasn't downloaded properly.

**Comment by Abhijeetm96** [comment]
There are packages that are outdated npm audit fix --force fixed the issue
