### ISSUE TITLE
Invalid Firebase API error

### ISSUE THREAD

**Issue by Rahulkasyap** [YogeshPrasanna/expense-manager-react#25]
![image](https://user-images.githubusercontent.com/52328131/60357326-f7cb3000-99f0-11e9-8fed-fbd5061c0410.png)
![image](https://user-images.githubusercontent.com/52328131/60357431-3fea5280-99f1-11e9-9be9-4f8866476dd5.png)
Even after providing the correct web API Key I am not able to authenticate nor sign in. 
On click of 
![image](https://user-images.githubusercontent.com/52328131/60357530-7f18a380-99f1-11e9-8fb8-6828070a1014.png)
I get a error message 

> {"error":{"code":400,"message":"API key not valid. Please pass a valid API key.","errors":[{"message":"API key not valid. Please pass a valid API key.","domain":"global","reason":"badRequest"}],"status":"INVALID_ARGUMENT"}}.

What couldbe the possible error.

**Comment by YogeshPrasanna** [comment]
Hey @Rahulkasyap 

In src/firebase/firebase.js 

you'll have to change the config - only api key will be coming from environmental variables (env.local)

Make sure you add the app in firebase and get the values from firebase config , i forgot to mention this in readme.

![add-app1](https://user-images.githubusercontent.com/18151732/60381884-c7c76f80-9a78-11e9-8fbd-ea03fbf3445a.png)

![adding-firebase1](https://user-images.githubusercontent.com/18151732/60381888-d31a9b00-9a78-11e9-9263-88a4083e99dc.png)

![adding-firebase2](https://user-images.githubusercontent.com/18151732/60381889-d57cf500-9a78-11e9-882b-827900ca1559.png)

Hope this solves the issue

**Comment by YogeshPrasanna** [comment]
i've added this in the readme now

**Comment by Abhijeetm96** [comment]
Hi @YogeshPrasanna 

Thanks for that. 

But adding the firebase credential came out with as set of error. Please help me in getting rid of them. 


![image](https://user-images.githubusercontent.com/41344280/60386762-27dd0680-9ab7-11e9-996b-004615a20bc3.png)
![image](https://user-images.githubusercontent.com/41344280/60386775-42af7b00-9ab7-11e9-9c05-e77f15ce72e5.png)
![image](https://user-images.githubusercontent.com/41344280/60386780-58bd3b80-9ab7-11e9-8138-6a795bd5b8c5.png)

**Comment by YogeshPrasanna** [comment]
Hey @Abhijeetm96 

I've resolved those issues now , and checked in the code 
Pull the latest code , you'll be able to run the application.

**Comment by Abhijeetm96** [comment]
Thanks @YogeshPrasanna

Can you explain what was the error?

**Comment by YogeshPrasanna** [comment]
Few months back , there was old expenses table - to migrate the data from old table to the new table ,
i was checking if that particular user had entries in that old table or not . so in that i was not checking if the data was !== null or not , it was a simple type error that  i missed out to check.

This was happening only in new firebase projects - like the one you created, and i could not find it out since i had legacy tables too.

**Comment by Abhijeetm96** [comment]
@YogeshPrasanna 

![image](https://user-images.githubusercontent.com/41344280/60387818-bb6a0380-9ac6-11e9-94c5-830f9211cc65.png)


The loan page has been in loading phase since a while. Even the add button is missing

**Comment by YogeshPrasanna** [comment]
Create this as a seperate issue , need to check
