### ISSUE TITLE
Logo Proposal for expense-manager-react

### ISSUE THREAD

**Issue by leonardoderoy** [YogeshPrasanna/expense-manager-react#4]
Hellow @YogeshPrasanna 
I'm a graphic designer and I like to support your project because I believe a good logo that reflects your project at its best can help the project publicity and trustability, also i'm an open source enthusiast. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Leonardo Deroy

Graphic Designer

**Comment by YogeshPrasanna** [comment]
Hi Leonard!

sure , a logo is really needed for this app.i just used some online tool to create the current logo , which is'nt looking good.

you can create the logo and send a PR .
thanks for the help :-)

**Comment by leonardoderoy** [comment]
hi @YogeshPrasanna  ok excellent I would like to know the exact name and what your project is about exactly for the creation of the logo

**Comment by YogeshPrasanna** [comment]
Hi @leonardoderoy 

Name : Expense Manager

The app helps users to log their daily expenses , and check on what category they are spending more .
The Loan Feature helps to track loans given or taken.

Basically there is two modes in the app - Day mode & Night mode 

so i donno how the logo is gonna fit in both modes , wether there should be different logo for each mode ?? 

![night_mode](https://user-images.githubusercontent.com/18151732/42305222-9688f0fc-8047-11e8-91ba-915ee4e7ef55.png)
![day_mode](https://user-images.githubusercontent.com/18151732/42305233-a7558c1a-8047-11e8-8c19-d888f68655e1.png)

Go through , the readme , and try out the app  .
try loggin some expenses and checkout :-) 👍 
https://sad-shirley-6ef62f.netlify.com/
